name: Publish Plugin

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Publish plugin
        run: ./gradlew publishPlugin
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}